/**
 * @momentum/db — the data-access layer.
 *
 *   src/database.types.ts   generated by `pnpm db:types`; never hand-edited
 *   src/mappers/            row ↔ domain type (@momentum/core/types)
 *   src/repositories/       functions over a user-scoped MomentumClient
 *
 * Nothing here may import React or Next (lint-enforced). Client construction
 * lives in apps/web/src/lib/supabase, because it is request- and
 * framework-shaped; this package only ever receives a client.
 *
 * Phase 2 ships the mappers for every table and the profiles repository, which
 * is the only one with a consumer today. Each later phase adds the repository
 * its feature needs, next to the queries that call it — the alternative is
 * guessing at query shapes for features that have not been designed yet.
 */
export * from "./types";
export * from "./mappers";
export * from "./repositories";
