import { z } from "zod";

import { isLocalDate, localDate } from "@momentum/core/time";
import { PROJECT_COLORS } from "@momentum/core/types";

/**
 * What the calendar's server actions accept.
 *
 * Two decisions shape every schema here.
 *
 * **Actions take wall-clock time, never instants.** A span arrives as
 * `{ date, startMinutes, endMinutes }` — the coordinates the grid actually works
 * in — and the server converts it with `fromLocal(date, minutes,
 * profile.timezone)`. The client is not allowed to assert an instant: the
 * profile timezone is the server's to apply (Domain Rule 4), and doing the
 * conversion in one place is what keeps the DST gap and overlap rules from
 * being re-decided per caller (Domain Rule 5).
 *
 * **Ids are client-generated.** A create carries the UUID the optimistic row
 * already uses, so the optimistic row and the persisted row share a key and a
 * retried insert collides with itself instead of creating a twin
 * (Domain Rule 17).
 */

/** A UUID the client generated with `crypto.randomUUID()`. */
const uuid = z.uuid("That is not a valid id.");

/**
 * `YYYY-MM-DD` in the user's timezone, narrowed to the branded `LocalDate` the
 * time module takes. Validated before it is branded, so `localDate()` — which
 * throws — is only ever reached with a string it accepts.
 */
const localDateField = z
  .string()
  .refine(isLocalDate, "Dates are YYYY-MM-DD.")
  .transform((value) => localDate(value));

/**
 * Wall-clock minutes from the day's 00:00.
 *
 * Bounded rather than free: `fromLocal` would happily normalise an overflow
 * into the next day, and silently creating a block on a day the user did not
 * point at is worse than refusing the input.
 *
 * A *start* is always inside its day. An *end* may not be: a block from 23:30
 * to 00:30 ends at 1470 minutes past its own midnight, `spanOf` returns exactly
 * that, and the editor is built to hold it — so capping the end at 1440 would
 * make every midnight-crossing block unsaveable through the one surface that
 * can edit it. One day of overflow is the whole allowance, because
 * `blocks_span_chk` already refuses anything longer than seven days and nothing
 * in the UI can produce a two-day block.
 */
const startMinuteOfDay = z
  .number()
  .int("Times are whole minutes.")
  .min(0, "That time is before the start of the day.")
  .max(1440, "That time is after the end of the day.");

const endMinuteOfDay = z
  .number()
  .int("Times are whole minutes.")
  .min(0, "That time is before the start of the day.")
  .max(2880, "A block cannot run more than a day past the time it started.");

/**
 * The bounded palette. A block with no colour of its own inherits its project's
 * and then its kind's default, which is resolved on read in `queries.ts`.
 */
const color = z.enum(PROJECT_COLORS).nullable();

/**
 * Neither length is a database constraint — `calendar_blocks` bounds only an
 * event's title to "not empty". They are the application's own hygiene, so an
 * accidental paste of a document into a title field fails next to the field
 * instead of becoming a row nothing can render.
 */
const title = z
  .string()
  .trim()
  .min(1, "Give the event a name.")
  .max(200, "Titles are at most 200 characters.");

const description = z
  .string()
  .trim()
  .max(2000, "Descriptions are at most 2000 characters.")
  .nullable();

/** The half-open wall-clock span every interaction produces. */
const span = {
  date: localDateField,
  startMinutes: startMinuteOfDay,
  endMinutes: endMinuteOfDay,
};

/**
 * `end > start`, mirroring `blocks_span_chk`. Checked here as well as in the
 * database so a zero-length drag comes back as a message on the form rather
 * than as a constraint violation the UI has to translate.
 */
function orderedSpan<T extends { startMinutes: number; endMinutes: number }>(schema: z.ZodType<T>) {
  return schema.refine((value) => value.endMinutes > value.startMinutes, {
    message: "A block has to end after it starts.",
    path: ["endMinutes"],
  });
}

/* -------------------------------------------------------------------------- */
/* Blocks                                                                     */
/* -------------------------------------------------------------------------- */

/**
 * Phase 3 creates events from the grid and nothing else. Work blocks come from
 * `scheduleTask` (they need a task), and habit blocks are generated by Phase 6;
 * `kind` is therefore a literal rather than the enum, so a crafted request
 * cannot ask this action for a shape it has no parent for.
 */
export const createBlockInput = orderedSpan(
  z.object({
    id: uuid,
    kind: z.literal("event"),
    title,
    description,
    color,
    ...span,
  }),
);

/**
 * Content only. Times move through `rescheduleBlock`, completion through
 * `setBlockCompletion`.
 *
 * `title` is optional because only an event has one to send. A work block
 * displays its task's title and a habit block its habit's, so the column stays
 * `''` for them and the parent's name keeps resolving on read (`queries.ts`) —
 * writing a copy of it here is what would silently stop the block tracking its
 * parent (Domain Rule 2). Absent rather than empty: `min(1)` still holds for
 * the event that does send one, so `blocks_event_title_chk` is never reached
 * from the application, and `blocks.update` simply omits the column.
 */
export const updateBlockInput = z.object({
  id: uuid,
  title: title.optional(),
  description,
  color,
});

/**
 * Move and resize are the same write: a drag that changes the day and the
 * duration at once is one row update, so the grid never shows a block that has
 * moved but not yet resized.
 */
export const rescheduleBlockInput = orderedSpan(z.object({ id: uuid, ...span }));

export const deleteBlockInput = z.object({ id: uuid });

/**
 * A task dropped on the grid becomes a work block linked to it (Domain Rule 2).
 * `id` is the new block's; `taskId` is the task it reserves time for. The block
 * carries no title of its own — it displays its task's, and the two stay in
 * step because there is only one of them.
 */
export const scheduleTaskInput = orderedSpan(z.object({ id: uuid, taskId: uuid, ...span }));

/**
 * Both flags are the UI's decision, not the database's (Domain Rule 13).
 *
 * `alsoCompleteTask` says this block is the task's only one, or its last
 * incomplete one, so completing it completes the task. `alsoUncompleteTask`
 * is its mirror: the block's task is complete, and un-completing the block
 * reopens it, because the two were one user action and it has to be
 * reversible. Each is meaningless in the other direction and the action
 * ignores it there.
 */
export const setBlockCompletionInput = z.object({
  id: uuid,
  completed: z.boolean(),
  alsoCompleteTask: z.boolean().default(false),
  alsoUncompleteTask: z.boolean().default(false),
  /**
   * Set when the block is a habit block, which routes the call to
   * `complete_habit_block` — the function that marks the span executed *and*
   * records the habit for the block's own day, in one transaction (Phase 6).
   *
   * It is a hint, not an authorisation: the database re-reads the block and
   * refuses with `22023` if it is not a habit block, so a client that sent this
   * for a work block gets an error rather than a second write path.
   */
  habitId: uuid.nullable().default(null),
});

/* -------------------------------------------------------------------------- */
/* Occurrences of a recurring event                                           */
/* -------------------------------------------------------------------------- */

/**
 * Editing one occurrence writes an override row keyed to the series and the
 * date the *rule* produced (docs/ARCHITECTURE.md §11) — not the date it is being
 * moved to, which is why `occurrenceDate` and `date` are separate fields and
 * routinely differ.
 *
 * Phase 3 does not build the recurring-event editor; it does have to let a user
 * drag one of these blocks, which is all these two schemas are for.
 */
export const rescheduleOccurrenceInput = orderedSpan(
  z.object({ seriesId: uuid, occurrenceDate: localDateField, ...span }),
);

/** Deleting one occurrence writes a cancelled override; the series is untouched. */
export const deleteOccurrenceInput = z.object({
  seriesId: uuid,
  occurrenceDate: localDateField,
});

export type CreateBlockInput = z.infer<typeof createBlockInput>;
export type UpdateBlockInput = z.infer<typeof updateBlockInput>;
export type RescheduleBlockInput = z.infer<typeof rescheduleBlockInput>;
export type DeleteBlockInput = z.infer<typeof deleteBlockInput>;
export type ScheduleTaskInput = z.infer<typeof scheduleTaskInput>;
export type SetBlockCompletionInput = z.infer<typeof setBlockCompletionInput>;
export type RescheduleOccurrenceInput = z.infer<typeof rescheduleOccurrenceInput>;
export type DeleteOccurrenceInput = z.infer<typeof deleteOccurrenceInput>;
